# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joe Rickerby
email: joe@joerick.me
description: > # this means to ignore newlines until "baseurl:"
  Joe Rickerby is a Mac and iOS developer in London, UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joerick.me" # the base hostname & protocol for your site
twitter_username: joerick
github_username:  joerick

twitter:
  username: joerick

social:
  name: Joe Rickerby
  links:
    - https://twitter.com/joerick
    - https://www.linkedin.com/in/joerick
    - https://github.com/joerick

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  work:
    output: true
    permalink: /work/:title/

defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
      section: work

gems:
  - jekyll-seo-tag