backend:
  name: github
  repo: joerick/joerick.me
  branch: master

media_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Post" # Used in the UI, e.g., "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category tags", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "work"
    label: "Work item"
    folder: "_work"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Platform", name: "platform", widget: "string"}
      - {label: "Technology", name: "technology", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
